config/routes.rb
Rails.application.routes.draw do

  namespace :movies do
    namespace :schedule do
      get 'list/index'
    end
  end
  namespace :movies do
    namespace :scenes do
      get 'print/create'
    end
  end
  namespace :movies do
    namespace :inventories do
      get 'print/create'
    end
  end
  get 'account/index'
  get 'pricing/index'
  authenticate :user, ->(u) { u.id } do
    require 'sidekiq/web'
    require 'sidekiq/cron/web'
    mount Sidekiq::Web => '/sidekiq'
  end


  get "/r/:shortlink_id/:shortlink_key", to: "shortlinks#show"

  devise_for :users
  root to: "home#index"
  resources :movies do
    resource :access_manager, only: :show, controller: "movies/access_manager" do
      resources :invites, controller: "movies/access_manager/invites" do
        collection do
          post "/new", to: "movies/access_manager/invites#create"
        end
      end
    end



    resource :simulation, only: [:create, :show], controller: "movies/simulation"
    resources :actors, controller: "movies/actors" do
      collection do
        get "/collect", to: "movies/actors/collector#show"
        post "/collect", to: "movies/actors/collector#create"
        get "/importer", to: "movies/actors/importer#index", as: "importer"
        delete "/importer/entry/:contact_entry_id", to: "movies/actors/importer#destroy", as: "delete_import_entry"
        get "/importer/entry/:contact_entry_id", to: "movies/actors/importer#show", as: "view_contact_entry"
        post "/importer/entry/:contact_entry_id", to: "movies/actors/importer#create", as: "import_contact_entry"
        get "/importer/entry/:contact_entry_id/import", to: "movies/actors/importer#new", as: "new_import_entry"
      end
    end

    resources :locations, controller: "movies/locations"
    resources :scenes, controller: "movies/scenes" do
      member do
        get "/print", to: "movies/scenes/print#create"
      end
    end
    resources :roles, controller: "movies/roles"
    resources :casts, controller: "movies/casts"
    resources :cars, controller: "movies/cars"
    resources :documents, controller: "movies/documents" do
      member do
        get "/download", to: "movies/documents/download#show"
      end
    end

    resources :inventories, controller: "movies/inventories" do
      resources :items, controller: "movies/inventories/items"
      member do
        get "/print", to: "movies/inventories/print#create"
      end
    end

    resource :budget, controller: "movies/budget" do
    end

    resources :movie_money_transfers, controller: "movies/budget"

    resource :schedule, controller: "movies/schedule" do
      get "/actor/:actor_id", to: "movies/schedule#for_actor", as: "actor"
      get "/events/:event/:day", to: "movies/schedule/events#create", as: "schedule_event"
      post "/:schedule_id/sort", to: "movies/schedule/sort#create"
      get "/list", to: "movies/schedule/list#index"
    end

    resources :schedule_events,  controller: "movies/schedule_events" do
      resources :ride_events,  controller: "movies/schedule_events/ride_events"
      resources :break_events,  controller: "movies/schedule_events/break_events"
      resources :shoot_events,  controller: "movies/schedule_events/shoot_events"
      resources :action_events,  controller: "movies/schedule_events/action_events"
    end
  end
end

app/models/actor.rb
class Actor < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :movie

  def color
  end
end

app/controllers/movies/actors/collector_controller.rb
class Movies::Actors::CollectorController < ApplicationController
  before_action :authenticate_user!
  before_action :set_movie
  layout "public"
  def show
    @contact = ActorContactEntry.new(movie_id: @movie.id)
  end

  def create
    @contact = ActorContactEntry.new(contact_params)
    @contact.movie_id = @movie.id
    return render :show unless @contact.save
  end

  private
  def contact_params
    params.require(:actor_contact_entry).permit(:firstname, :lastname, :phonenumber, :email, :allergenes, :street, :location, :postalcode, :dob)
  end
end

app/controllers/movies/actors/importer_controller.rb
class Movies::Actors::ImporterController < ApplicationController
  before_action :authenticate_user!
  before_action :set_movie
  before_action :set_contact_entry, only: [:new, :show, :create, :destroy]
  before_action :set_fields

  def index
    @contact_entries = @movie.actor_contact_entries
  end

  def create
    @actor = @movie.actors.find(params[:actor_id])
    @fields.each do |field|
      if params["import_#{field.to_s}"]
        @actor.send("#{field.to_s}=", @contact_entry.send(field))
      end
    end
    @actor.save
    flash[:success] = "Imported fields successfully"
    return redirect_to importer_movie_actors_path(@movie)
  end

  def show

  end

  def destroy
    @contact_entry.destroy
    flash[:success] = "Contact Submission deleted"
    return redirect_to importer_movie_actors_path(@movie)

  end

  def new
    @actor = @movie.actors.find(params[:actor_id]) if params[:actor_id]
  end

  def set_fields
    @fields = [:firstname, :lastname, :email, :phonenumber, :street, :location, :allergenes]
  end

  def set_contact_entry
    @contact_entry = @movie.actor_contact_entries.find(params[:contact_entry_id])
  end
end

app/controllers/movies/actors_controller.rb
class Movies::ActorsController < ApplicationController
  before_action :set_movie
  before_action :set_actor, only: [:destroy, :update, :edit, :show, :destroy]
  before_action :authenticate_user!
  def edit
  end

  def index
    @actors = @movie.actors
    @collect_info_url = "https://bupl.net/movies/#{@movie.id}/actors/collect"
    @qrcode = RQRCode::QRCode.new(@collect_info_url)
  end

  def create
    @actor = @movie.actors.new(actor_params)


    return redirect_to movie_actor_path(@movie, @actor) if @actor.save

    render json: @actor.errors
  end

  def show
  end

  def destroy
    @actor.delete
    redirect_to movie_actors_path(@movie)
  end

  def update
    @actor.update(actor_params)
    redirect_to movie_actor_path(@movie, @actor)
  end

  def new
    @actor = @movie.actors.new
  end

  private
  def actor_params
    params.require(:actor).permit(:firstname, :lastname, :email, :street, :allergenes, :postalcode, :city)
  end

  def set_actor
    @actor = Actor.find(params[:id])
  end
end

app/helpers/movies/actors/collector_helper.rb
module Movies::Actors::CollectorHelper
end

app/helpers/movies/actors/importer_helper.rb
module Movies::Actors::ImporterHelper
  def field_for model, field
    "<div class='field'>
    <strong>#{field.to_s.titleize}</strong>
    <p class='text-muted'>
    #{model.send(field)}<br>
    </p>
    </div>"
  end

  def fields_for model, fields
    src = ""
    fields.each do |field|
      src += field_for(model, field)
    end
    raw src
  end
end

app/views/movies/actors/importer/index.html.erb
<%= content_for :title do %>Contact Importer<% end %>



<% if @contact_entries.size %>
  <table class="table table-striped table-bordered">
    <thead>
    <tr>
      <th>Name</th>
      <th colspan="4"></th>
    </tr>
    </thead>
    <tbody>
    <% @contact_entries.each do |ce| %>
      <tr>
        <td><%= ce.firstname %> <%= ce.lastname %></td>
        <td><%= link_to 'Import', new_import_entry_movie_actors_path(@movie, ce) %></td>
        <td><%= link_to 'Destroy',delete_import_entry_movie_actors_path(@movie, ce), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% end %>

app/views/movies/actors/importer/new.html.erb
<%= content_for :title do %>Import Entry #<%= @contact_entry.id %><% end %>
<%
  fields = @fields
%>
<% if @actor %>
  <%= form_tag import_contact_entry_movie_actors_path(@movie, @contact_entry) do %>

    <input type="hidden" name="actor_id" value="<%= @actor.id %>">
<div class="row">
  <div class="col-sm-5">
    <%= fields_for @contact_entry, fields %>
  </div>
  <div class="col-sm-2">
    <% fields.each do |field| %>
      <div class="import-toggle">
        <input type="hidden" name="import_<%= field.to_s %>" value="1">
        <%= image_tag "sync_arrow", height: 30 %>
        <%= image_tag "no_import", height: 30, class: "d-none" %>
      </div>
    <% end %>
  </div>
  <div class="col-sm-5">
    <div class="field">
      <%= fields_for @actor, fields %>
    </div>
  </div>
</div>
    <button type="submit" class="btn btn-primary">Import fields</button>
  <% end %>
<% else %>
  <div class="row">
    <div class="col-sm-5">
      <h2>Entry</h2>
      <%= fields_for @contact_entry, fields %>
    </div>
    <div class="col-sm-2">

    </div>
    <div class="col-sm-5">
      <div class="form-group">
        <b>Select an author</b>
        <form id="setAuthorForm" action="<%= new_import_entry_movie_actors_path %>">
          <%= select_tag :actor_id, options_for_select(["---------------------------------------------"] + (@movie.actors.all.map { |u| [u.firstname + " " + u.lastname, u.id] })),
                        { name: "actor_id", class: 'chosen-select', onchange: "window.setAuthorForm.submit()" }
        %>
        </form>
      </div>
    </div>
  </div>
<% end %>