config/routes.rb
Rails.application.routes.draw do

  namespace :movies do
    namespace :schedule do
      get 'list/index'
    end
  end
  namespace :movies do
    namespace :scenes do
      get 'print/create'
    end
  end
  namespace :movies do
    namespace :inventories do
      get 'print/create'
    end
  end
  get 'account/index'
  get 'pricing/index'
  authenticate :user, ->(u) { u.id } do
    require 'sidekiq/web'
    require 'sidekiq/cron/web'
    mount Sidekiq::Web => '/sidekiq'
  end


  get "/r/:shortlink_id/:shortlink_key", to: "shortlinks#show"

  devise_for :users
  root to: "home#index"
  resources :movies do
    resource :access_manager, only: :show, controller: "movies/access_manager" do
      resources :invites, controller: "movies/access_manager/invites" do
        collection do
          post "/new", to: "movies/access_manager/invites#create"
        end
      end
    end



    resource :simulation, only: [:create, :show], controller: "movies/simulation"
    resources :actors, controller: "movies/actors" do
      collection do
        get "/collect", to: "movies/actors/collector#show"
        post "/collect", to: "movies/actors/collector#create"
        get "/importer", to: "movies/actors/importer#index", as: "importer"
        delete "/importer/entry/:contact_entry_id", to: "movies/actors/importer#destroy", as: "delete_import_entry"
        get "/importer/entry/:contact_entry_id", to: "movies/actors/importer#show", as: "view_contact_entry"
        post "/importer/entry/:contact_entry_id", to: "movies/actors/importer#create", as: "import_contact_entry"
        get "/importer/entry/:contact_entry_id/import", to: "movies/actors/importer#new", as: "new_import_entry"
      end
    end

    resources :locations, controller: "movies/locations"
    resources :scenes, controller: "movies/scenes" do
      member do
        get "/print", to: "movies/scenes/print#create"
      end
    end
    resources :roles, controller: "movies/roles"
    resources :casts, controller: "movies/casts"
    resources :cars, controller: "movies/cars"
    resources :documents, controller: "movies/documents" do
      member do
        get "/download", to: "movies/documents/download#show"
      end
    end

    resources :inventories, controller: "movies/inventories" do
      resources :items, controller: "movies/inventories/items"
      member do
        get "/print", to: "movies/inventories/print#create"
      end
    end

    resource :budget, controller: "movies/budget" do
    end

    resources :movie_money_transfers, controller: "movies/budget"

    resource :schedule, controller: "movies/schedule" do
      get "/actor/:actor_id", to: "movies/schedule#for_actor", as: "actor"
      get "/events/:event/:day", to: "movies/schedule/events#create", as: "schedule_event"
      post "/:schedule_id/sort", to: "movies/schedule/sort#create"
      get "/list", to: "movies/schedule/list#index"
    end

    resources :schedule_events,  controller: "movies/schedule_events" do
      resources :ride_events,  controller: "movies/schedule_events/ride_events"
      resources :break_events,  controller: "movies/schedule_events/break_events"
      resources :shoot_events,  controller: "movies/schedule_events/shoot_events"
      resources :action_events,  controller: "movies/schedule_events/action_events"
    end
  end
end

app/models/scene.rb
class Scene < ApplicationRecord
  belongs_to :inventory, optional: true
  has_and_belongs_to_many :roles
  has_and_belongs_to_many :items
end

app/controllers/movies/access_manager/invites_controller.rb
class Movies::AccessManager::InvitesController < ApplicationController
  before_action :set_movie

  def new
    @permissions = Permission.all
  end

  def create
    return render text: "Not supported."
    user = User.find_by_email(params[:email])

    return handle_existing_user(user) if user
    handle_new_user()
  end

  def handle_existing_user(user)

  end

  def handle_new_user

  end
end

app/controllers/movies/access_manager_controller.rb
class Movies::AccessManagerController < ApplicationController
  before_action :set_movie
  before_action :authenticate_user!
  def show
  end
end

app/controllers/movies/actors/collector_controller.rb
class Movies::Actors::CollectorController < ApplicationController
  before_action :authenticate_user!
  before_action :set_movie
  layout "public"
  def show
    @contact = ActorContactEntry.new(movie_id: @movie.id)
  end

  def create
    @contact = ActorContactEntry.new(contact_params)
    @contact.movie_id = @movie.id
    return render :show unless @contact.save
  end

  private
  def contact_params
    params.require(:actor_contact_entry).permit(:firstname, :lastname, :phonenumber, :email, :allergenes, :street, :location, :postalcode, :dob)
  end
end

app/controllers/movies/actors/importer_controller.rb
class Movies::Actors::ImporterController < ApplicationController
  before_action :authenticate_user!
  before_action :set_movie
  before_action :set_contact_entry, only: [:new, :show, :create, :destroy]
  before_action :set_fields

  def index
    @contact_entries = @movie.actor_contact_entries
  end

  def create
    @actor = @movie.actors.find(params[:actor_id])
    @fields.each do |field|
      if params["import_#{field.to_s}"]
        @actor.send("#{field.to_s}=", @contact_entry.send(field))
      end
    end
    @actor.save
    flash[:success] = "Imported fields successfully"
    return redirect_to importer_movie_actors_path(@movie)
  end

  def show

  end

  def destroy
    @contact_entry.destroy
    flash[:success] = "Contact Submission deleted"
    return redirect_to importer_movie_actors_path(@movie)

  end

  def new
    @actor = @movie.actors.find(params[:actor_id]) if params[:actor_id]
  end

  def set_fields
    @fields = [:firstname, :lastname, :email, :phonenumber, :street, :location, :allergenes]
  end

  def set_contact_entry
    @contact_entry = @movie.actor_contact_entries.find(params[:contact_entry_id])
  end
end

app/controllers/movies/actors_controller.rb
class Movies::ActorsController < ApplicationController
  before_action :set_movie
  before_action :set_actor, only: [:destroy, :update, :edit, :show, :destroy]
  before_action :authenticate_user!
  def edit
  end

  def index
    @actors = @movie.actors
    @collect_info_url = "https://bupl.net/movies/#{@movie.id}/actors/collect"
    @qrcode = RQRCode::QRCode.new(@collect_info_url)
  end

  def create
    @actor = @movie.actors.new(actor_params)


    return redirect_to movie_actor_path(@movie, @actor) if @actor.save

    render json: @actor.errors
  end

  def show
  end

  def destroy
    @actor.delete
    redirect_to movie_actors_path(@movie)
  end

  def update
    @actor.update(actor_params)
    redirect_to movie_actor_path(@movie, @actor)
  end

  def new
    @actor = @movie.actors.new
  end

  private
  def actor_params
    params.require(:actor).permit(:firstname, :lastname, :email, :street, :allergenes, :postalcode, :city)
  end

  def set_actor
    @actor = Actor.find(params[:id])
  end
end

app/controllers/movies/budget_controller.rb
class Movies::BudgetController < ApplicationController
  before_action :set_movie
  before_action :authenticate_user!
  def show
    @transfers = @movie.movie_money_transfers
    @current_balance = @transfers.where(:budget_type => "income").sum(:budget_amount) - @transfers.where(:budget_type => "withdrawal").sum(:budget_amount)
  end

  def new
    @transfer = @movie.movie_money_transfers.new
  end

  def create
    @transfer = @movie.movie_money_transfers.new(budget_params)
    @transfer.user_id = current_user.id
    @transfer.budget_type = params[:budget_type]
    @transfer.budget_amount = (params[:movie_money_transfer][:budget_amount].to_f * 100)
    @transfer.save
    redirect_to movie_budget_path(@movie)
  end

  def destroy
    @transfer = @movie.movie_money_transfers.find(params[:id]).delete
    redirect_to movie_budget_path(@movie)
  end

  def budget_params
    params.require(:movie_money_transfer).permit(:budget_amount, :budget_type, :title, :actor_id, :item_id)
  end
end

app/controllers/movies/budgets_controller.rb
class Movies::BudgetsController < ApplicationController
  before_action :set_movie
  before_action :authenticate_user!

  def edit
  end

  def index
  end

  def show
  end

  def destroy
  end

  def update
  end

  def new
  end
end

app/controllers/movies/cars_controller.rb
class Movies::CarsController < ApplicationController
  before_action :set_movie
  before_action :set_car, only: [:destroy, :update, :edit, :show, :destroy]
  before_action :authenticate_user!
  def edit
  end

  def index
    @cars = @movie.cars
  end

  def create
    @car = @movie.cars.new(car_params)


    return redirect_to movie_car_path(@movie, @car) if @car.save

    render json: @car.errors
  end

  def show
  end

  def destroy
    @car.delete
    redirect_to movie_cars_path(@movie)
  end

  def update
    @car.update(car_params)
    redirect_to movie_car_path(@movie, @car)
  end

  def new
    @car = @movie.cars.new
  end

  private
  def car_params
    params.require(:car).permit(:name, :vendor, :license_plate, :available_seats, :fuel, :movie_id, :actor_id)
  end

  def set_car
    @car = Car.find(params[:id])
  end
end

app/controllers/movies/casts_controller.rb
class Movies::CastsController < ApplicationController
  before_action :set_movie
  before_action :authenticate_user!
  def edit
  end

  def index
  end

  def show
  end

  def destroy
  end

  def update
  end

  def new
  end
end

app/controllers/movies/documents/download_controller.rb
class Movies::Documents::DownloadController < ApplicationController
  before_action :set_movie
  before_action :set_document
  def show
    redirect_to rails_blob_path(@document.file, disposition: 'attachment')
  end

  def set_document
    @document = @movie.documents.find(params[:id])
  end
end

app/controllers/movies/documents_controller.rb
class Movies::DocumentsController < ApplicationController
  before_action :authenticate_user!
  skip_before_action :verify_authenticity_token, only: :create
  before_action :set_movie
  def edit
  end

  def index
    @documents = @movie.documents
  end

  def create
    document = @movie.documents.create!({
      user: current_user
    })
    document.file.attach(params[:file])
    document.save
    render json: document
  end

  def show

  end

  def destroy
    @document = @movie.documents.find(params[:id])
    @document.destroy
    flash[:success] = "Document deleted"
    redirect_to movie_documents_path(@movie)
  end

  def update
  end

  def new
  end
end

app/controllers/movies/inventories/items_controller.rb
class Movies::Inventories::ItemsController < ApplicationController
  before_action :set_movie
  before_action :set_inventory
  before_action :authenticate_user!
  before_action :set_item, only: [:destroy, :edit, :update]
  def create
    @item = @inventory.items.create(item_params)
    if @item.errors
      return redirect_to new_movie_inventory_item_path(@movie, @inventory)
    end
    redirect_to movie_inventory_path(@movie, @inventory)
  end

  def new
    @item = @inventory.items.new
  end

  def update
    @item.update(item_params)
    flash[:success] = "Item saved"
    return redirect_to edit_movie_inventory_item_path(@movie, @inventory)
  end

  def edit

  end

  def destroy
    @item.destroy
    redirect_to movie_inventory_path(@movie, @inventory)
  end

  def set_inventory
    @inventory = @movie.inventories.find(params[:inventory_id])
  end

  def item_params
    params.require(:item).permit(:license_plate, :car_owner_id, :name, scene_ids: [])
  end

  def set_item
    @item = @inventory.items.find(params[:id])
  end
end

app/controllers/movies/inventories/print_controller.rb
class Movies::Inventories::PrintController < ApplicationController
  before_action :set_movie
  before_action :set_inventory
  before_action :authenticate_user!
  layout "pdf"
  def create

  end



  def set_inventory
    @inventory = Movie.find(params[:movie_id]).inventories.find(params[:id])
  end
end

app/controllers/movies/inventories_controller.rb
class Movies::InventoriesController < ApplicationController
  before_action :set_movie
  before_action :set_inventory, only: [:destroy, :update, :edit, :show, :destroy]
  before_action :authenticate_user!
  def edit
  end

  def index
    @inventories = @movie.inventories
  end

  def create
    @inventory = @movie.inventories.new(inventory_params)

    return redirect_to movie_inventory_path(@movie, @inventory) if @inventory.save

    render json: @inventory.errors
  end

  def show
  end



  def destroy
    @inventory.delete
    redirect_to movie_inventories_path(@movie)
  end

  def update
    @inventory.update(inventory_params)
    redirect_to movie_inventory_path(@movie, @inventory)
  end

  def new
    @inventory = @movie.inventories.new
  end

  private
  def inventory_params
    params.require(:inventory).permit(:name, :inventory_type)
  end

  def set_inventory
    @inventory = Inventory.find(params[:id])
  end
end

app/controllers/movies/locations_controller.rb
class Movies::LocationsController < ApplicationController
  before_action :set_movie
  before_action :set_location, only: [:destroy, :update, :edit, :show, :destroy]
  before_action :authenticate_user!
  def edit
  end

  def index
    @locations = @movie.locations
  end

  def create
    @location = @movie.locations.new(location_params)


    return redirect_to movie_location_path(@movie, @location) if @location.save

    render json: @location.errors
  end

  def show
  end

  def destroy
    @location.delete
    redirect_to movie_locations_path(@movie)
  end

  def update
    @location.update(location_params)
    redirect_to movie_location_path(@movie, @location)
  end

  def new
    @location = @movie.locations.new
  end

  private
  def location_params
    params.require(:location).permit(:name, :required_attendance, :for_sleeping, :lat, :lng)
  end

  def set_location
    @location = Location.find(params[:id])
  end
end

app/controllers/movies/roles_controller.rb
class Movies::RolesController < ApplicationController
  before_action :set_movie
  before_action :set_role, only: [:destroy, :update, :edit, :show, :destroy]
  before_action :authenticate_user!
  def edit
  end

  def index
    @roles = @movie.roles
  end

  def create
    @role = @movie.roles.new(role_params)


    return redirect_to movie_roles_path(@movie) if @role.save

    render json: @role.errors
  end

  def show
  end

  def destroy
    @role.delete
    redirect_to movie_roles_path(@movie)
  end

  def update
    @role.update(role_params)
    redirect_to movie_role_path(@movie, @role)
  end

  def new
    @role = @movie.roles.new
  end

  private
  def role_params
    params.require(:role).permit(:name)
  end

  def set_role
    @role = Role.find(params[:id])
  end
end

app/controllers/movies/scenes/print_controller.rb
class Movies::Scenes::PrintController < ApplicationController
  before_action :set_movie
  before_action :set_scene

  layout "pdf"
  def create

  end



  def set_scene
    @scene = Movie.find(params[:movie_id]).scenes.find(params[:id])
  end
end

app/controllers/movies/scenes_controller.rb
class Movies::ScenesController < ApplicationController
  before_action :set_movie
  before_action :set_scene, only: [:destroy, :update, :edit, :show, :destroy]
  before_action :authenticate_user!
  def edit
  end

  def index
    @scenes = @movie.scenes
  end

  def create
    @scene = @movie.scenes.new(scene_params)


    return redirect_to movie_scene_path(@movie, @scene) if @scene.save

    render json: @scene.errors
  end

  def show
  end

  def destroy
    @scene.delete
    redirect_to movie_scenes_path(@movie)
  end

  def update
    @scene.update(scene_params)
    redirect_to movie_scene_path(@movie, @scene)
  end

  def new
    @scene = @movie.scenes.new
  end

  private
  def scene_params
    params.require(:scene).permit(:name, :description, role_ids: [], item_ids: [])
  end

  def set_scene
    @scene = Scene.find(params[:id])
  end
end

app/controllers/movies/schedule/events_controller.rb
class Movies::Schedule::EventsController < ApplicationController
  before_action :set_movie
  before_action :authenticate_user!
  def create
    # TODO: sanitize
    @event = params[:event].constantize.new
    day = Date.parse(params[:day])
    @schedule_event = @movie.schedule.schedule_events.create(
                                       scheduled_on: day,
                                       schedulable: @event
    )
  end
end

app/views/movies/scenes/_form.html.erb
<%= form_for [@movie, @scene] do |form| %>
  <% if movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
        <% movie.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-sm-6">
      <div class="form-group">
        <%= form.label :name %>
        <%= form.text_field :name, class: "form-control" %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-12">
      <div class="form-group">
        <%= form.label :description %>
        <%= form.text_area :description, class: "form-control", :rows => 20 %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-6">
      <b>Roles</b>
      <p class="text-muted">Select the roles which are required for the scene</p>
      <table class="table table-striped table-bordered">
        <thead>
        <tr>
          <th><i class="fa fa-check"></i></th>
          <th>Name</th>
        </tr>
        </thead>
        <tbody>
        <% @movie.roles.all.each do |role| %>
          <tr>
            <td width="1">
              <%= check_box_tag "scene[role_ids][]", role.id, form.object.roles.include?(role) %>
            </td>
            <td>
              <label><%= role.name %></label>
            </td>
          </tr>
        <% end %>
        </tbody>
        </table>
    </div>
    <div class="col-sm-6">
      <b>Items</b>
      <p class="text-muted">Select the items which are required for the scene</p>
      <table class="table table-striped table-bordered">
        <thead>
        <tr>
          <th><i class="fa fa-check"></i></th>
          <th>Name</th>
        </tr>
        </thead>
        <tbody>
        <% @movie.items.all.each do |item| %>
          <tr>
            <td width="1">
              <%= check_box_tag "scene[item_ids][]", item.id, form.object.items.include?(item) %>
            </td>
            <td>
              <label><%= item.name %></label>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>

  <div class="content-wrapper-footer">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/movies/scenes/destroy.html.erb
<h1>Movies::scenes#destroy</h1>
<p>Find me in app/views/movies/scenes/destroy.html.erb</p>

app/views/movies/scenes/edit.html.erb
<%= content_for :title do %>Edit <%= @scene.name %><% end %>
<%= render 'form', movie: @movie, role: @scene %>

app/views/movies/scenes/index.html.erb
<%= content_for :breadcrumbs do
  breadcrumbs([[movie_path(@movie), @movie.title], [movie_scenes_path(@movie), "Scenes"]])
end
%>
<%= content_for :title do %>
  Scenes
<% end %>


<% if @scenes.size == 0 %>
  <%= empty_resource Scene, cta: new_movie_scene_path %>
<% end %>

<% if @scenes.size > 0 %>
  <div class="table-responsive">
    <table class="table table-striped table-bordered">
      <thead>
      <tr>
        <th>Name</th>
        <th colspan="4"></th>
      </tr>
      </thead>
      <tbody>
      <% @scenes.each do |scene| %>
        <tr>
          <td><%= scene.name %></td>
          <td><%= link_to 'Print', print_movie_scene_path(@movie, scene) %></td>
          <td><%= link_to 'Show', movie_scene_path(@movie, scene) %></td>
          <td><%= link_to 'Edit', edit_movie_scene_path(@movie, scene) %></td>
          <td><%= link_to 'Destroy', movie_scene_path(@movie, scene), method: :delete, data: {confirm: 'Are you sure?'} %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
<% end %>

<div class="content-wrapper-footer">
  <%= link_to "Create", new_movie_scene_path(@movie), class: "btn btn-xs btn-primary" %>
</div>

app/views/movies/scenes/new.html.erb
<%= content_for :title do %>New scene<% end %>
<%= render 'form', movie: @movie, scene: @scene %>

app/views/movies/scenes/show.html.erb
<%= content_for :breadcrumbs do
  breadcrumbs([[movie_path(@movie), @movie.title], [movie_scenes_path(@movie), "Scenes"], [movie_scene_path(@movie, @scene), @scene.name]])
end
%>
<%= content_for :title do %>
  Scene <%= @scene.name %>
<% end %>

Description<br>
<p class="text-muted"><%= @scene.description || "-" %></p>

<hr>
<div class="row">
  <div class="col-xs-12 col-sm-6">
    Roles
    <div>
      <% @scene.roles.each do |role| %>
        <div><span class="badge badge-primary"><%= role.name %></span></div>
      <% end %>
      <% if @scene.roles.size == 0 %>
        <p class="text-muted empty-message">No roles required</p>
      <% end %>
    </div>
  </div>
  <div class="col-xs-12 col-sm-6">
    Items
    <div>
      <% @scene.items.each do |item| %>
        <div><span class="badge badge-primary"><%= item.name %></span></div>
      <% end %>
      <% if @scene.items.size == 0 %>
        <p class="text-muted empty-message">No items required</p>
      <% end %>
    </div>
  </div>
</div>
<hr>

<%= link_to :edit, edit_movie_scene_url(@movie, @scene), class: "btn btn-primary" %>

app/views/movies/scenes/update.html.erb
<h1>Movies::scenes#update</h1>
<p>Find me in app/views/movies/scenes/update.html.erb</p>